name: Build and Deploy to ACK

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: custom-container
  IMAGE: sae
  TAG: ${{ github.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          region-id: "${{ env.REGION_ID }}"
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

      # 1.2 Buid and push image to ACR
      - name: Build and push image to ACR
        run: |
          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

      # 1.3 et Docker Image to Env
      - name: Set Docker Image to Env
        run: echo "DOCKER_IMAGE=$REGISTRY/$NAMESPACE/$IMAGE:$TAG" >> $GITHUB_ENV


      # 2.1 Install Serverless Devs
      - name: Install Serverless Devs
        uses: actions/setup-node@v2
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
        run: npm install -g @serverless-devs/s


      # 2.1 Config Serverless Devs
      - name: Config Serverless Devs
        run: s config add --AccountID ${{secrets.Account_ID}} --AccessKeyID ${{secrets.ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.ACCESS_KEY_SECRET}} -a publish_access

      # 2.2 Deploy to SAE
      - name: Deploy to SAE
        run: s deploy